# Generated by Django 3.0.8 on 2020-11-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=60)),
                ('employee_salary', models.CharField(max_length=60)),
                ('employee_age', models.CharField(max_length=60)),
                ('profile_image', models.CharField(max_length=60)),
                ('id_no', models.CharField(max_length=60)),
            ],
        ),
    ]
